"""
test_report_hygiene.py — Verification of strict report provenance and hygiene.

Enforces:
  1. Root RESULTS.md must be auto-generated by code from a single named run directory.
  2. Header metadata (Run ID, Git commit, label, partitions, rounds) must match the run data.
  3. No sections or tables may be hand-appended from other runs.
  4. Root RESULTS.md must be reproducible by generate_report.py from its named run directory.
"""

from __future__ import annotations

from pathlib import Path
import re
import unittest

from src.experiments.generate_report import generate_report


class TestReportHygiene(unittest.TestCase):
    def setUp(self):
        self.root_results = Path("RESULTS.md")
        self.assertTrue(self.root_results.exists(), "Root RESULTS.md must exist")
        self.content = self.root_results.read_text(encoding="utf-8")

    def test_root_results_header_structure(self):
        """Root RESULTS.md must have standard auto-generated header with valid Run ID."""
        self.assertTrue(
            self.content.startswith("# AUTO-GENERATED, do not edit by hand"),
            "RESULTS.md must start with '# AUTO-GENERATED, do not edit by hand'",
        )

        match = re.search(r"# Run ID:\s*([^\s\n]+)", self.content)
        self.assertIsNotNone(match, "RESULTS.md must specify '# Run ID: <run_id>'")
        run_id = match.group(1)

        run_dir = Path("results/runs") / run_id
        self.assertTrue(
            run_dir.exists() and run_dir.is_dir(),
            f"Run directory results/runs/{run_id} specified in header must exist on disk",
        )

    def test_no_foreign_run_sections_or_citations(self):
        """Verifies that root RESULTS.md contains NO hand-appended sections citing other run dirs."""
        match = re.search(r"# Run ID:\s*([^\s\n]+)", self.content)
        self.assertIsNotNone(match)
        active_run_id = match.group(1)

        # Search for any references to results/runs/<other_id>
        run_citations = re.findall(r"results/runs/([a-zA-Z0-9_\-]+)", self.content)
        for cited_id in run_citations:
            self.assertEqual(
                cited_id,
                active_run_id,
                f"RESULTS.md for run '{active_run_id}' contains foreign run citation 'results/runs/{cited_id}'",
            )

        # Search for any header-like markers indicating hand-stitched reports
        self.assertEqual(
            self.content.count("# AUTO-GENERATED"),
            1,
            "RESULTS.md must contain exactly ONE generator banner (no stitched reports)",
        )

    def test_root_results_code_reproducibility(self):
        """Verifies that running generate_report on the header's run directory reproduces RESULTS.md."""
        match = re.search(r"# Run ID:\s*([^\s\n]+)", self.content)
        self.assertIsNotNone(match)
        active_run_id = match.group(1)
        run_dir = Path("results/runs") / active_run_id

        # Generate fresh report content in-memory
        fresh_report = generate_report(run_dir, output_path=None, update_root=False)

        # Extract table rows (excluding dynamic timestamp line)
        def strip_timestamp(text: str) -> list[str]:
            return [line for line in text.splitlines() if not line.startswith("# Date:")]

        root_lines = strip_timestamp(self.content)
        fresh_lines = strip_timestamp(fresh_report)

        self.assertEqual(
            root_lines,
            fresh_lines,
            "Root RESULTS.md diverges from code generated output for its Run ID",
        )

    def test_past_reports_in_reports_dir(self):
        """Verifies that all archived reports in reports/ have valid corresponding headers."""
        reports_dir = Path("reports")
        if not reports_dir.exists():
            return

        for r_file in reports_dir.glob("*/RESULTS.md"):
            r_text = r_file.read_text(encoding="utf-8")
            match = re.search(r"# Run ID:\s*([^\s\n]+)", r_text)
            self.assertIsNotNone(match, f"Archived report {r_file} must have a valid Run ID header")
            archived_id = match.group(1)
            self.assertEqual(
                archived_id,
                r_file.parent.name,
                f"Archived report in {r_file.parent.name} has mismatched Run ID '{archived_id}'",
            )


if __name__ == "__main__":
    unittest.main()
